// jobOptions.js

const jobOptions = [
    // Healthcare
    "Doctor",
    "Nurse",
    "Dentist",
    "Pharmacist",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech Therapist",
    "Radiologist",
    "Surgeon",
    "Psychiatrist",
    // Engineering and Technology
    "Engineer",
    "Software Developer",
    "Web Developer",
    "Data Scientist",
    "Network Administrator",
    "Systems Analyst",
    "Cybersecurity Analyst",
    "UX/UI Designer",
    "Database Administrator",
    "IT Project Manager",
    // Business and Finance
    "Accountant",
    "Financial Analyst",
    "Investment Banker",
    "Management Consultant",
    "Business Development Manager",
    "Marketing Manager",
    "Human Resources Manager",
    "Operations Manager",
    "Sales Manager",
    "Risk Manager",
    // Education
    "Teacher",
    "Professor",
    "Lecturer",
    "School Principal",
    "Guidance Counselor",
    "Librarian",
    "Education Administrator",
    "Curriculum Developer",
    "Special Education Teacher",
    "Education Consultant",
    "Researcher",
    // Legal
    "Lawyer",
    "Judge",
    "Paralegal",
    "Legal Secretary",
    "Legal Consultant",
    "Corporate Counsel",
    "Legal Analyst",
    "Public Defender",
    "Intellectual Property Attorney",
    "Arbitrator",
    // Arts and Entertainment
    "Artist",
    "Musician",
    "Actor",
    "Dancer",
    "Photographer",
    "Filmmaker",
    "Writer",
    "Fashion Designer",
    "Graphic Designer",
    "Game Designer",
    // Sales and Marketing
    "Sales Manager",
    "Marketing Manager",
    "Advertising Executive",
    "Public Relations Manager",
    "Brand Manager",
    "Market Research Analyst",
    "Social Media Manager",
    "Sales Representative",
    "Copywriter",
    "Event Planner",
    // Science and Research
    "Scientist",
    "Biologist",
    "Chemist",
    "Physicist",
    "Astronomer",
    "Ecologist",
    "Geologist",
    "Research Analyst",
    "Data Analyst",
    "Lab Technician",
    // Government and Public Service
    "Politician",
    "Civil Servant",
    "Diplomat",
    "Policy Analyst",
    "Social Worker",
    "Nonprofit Manager",
    "Urban Planner",
    "Environmental Officer",
    "Intelligence Analyst",
    "Foreign Service Officer",
    // Hospitality and Tourism
    "Hotel Manager",
    "Chef",
    "Restaurant Owner",
    "Event Coordinator",
    "Travel Agent",
    "Tour Guide",
    "Cruise Ship Director",
    "Sommelier",
    "Hotel Concierge",
    "Bartender",
    // Engineering and Construction
    "Architect",
    "Civil Engineer",
    "Structural Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Environmental Engineer",
    "Construction Manager",
    "Quantity Surveyor",
    "Building Inspector",
    "Urban Designer",
    // Media and Communication
    "Journalist",
    "Editor",
    "News Anchor",
    "Public Relations Specialist",
    "Content Writer",
    "Copyeditor",
    "Technical Writer",
    "Radio Broadcaster",
    "TV Producer",
    "Media Planner",
    // Sports and Fitness
    "Athlete",
    "Coach",
    "Fitness Instructor",
    "Sports Agent",
    "Sports Marketer",
    "Physical Education Teacher",
    //Others
    "Student",
    "Others"
];

export default jobOptions;